### ISSUE TITLE
App Shows dialogue for "Close App"

### ISSUE THREAD

**Issue by govindtank** [guiguegon/GalleryModule#11]
@guiguegon 

similar to issue#9 

i was Using the GalleryModule library in my application for taking pictures and selecting it to send it to server,
App is working fine in (Xiaomi redmi note 3, Android 6.0), everything works great, clicking photos and selecting multiple images,
 but when i tried the same app with Motorola G4 plus device(Android 7.0), it works fine if i select images (even multiple images), but if i start the camera and open camera it shows dialogue box (even without pressing any camera click button, it just crashes at that time) which tells me to close the app, and app crashes that time.
don't able to find a problem cause!

below is the copied log from when i start the camera till the crashing the app :

20574-20586/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] queueBuffer: BufferQueue has been abandoned
20574-20574/stimulus.openforbusiness E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 584064)
20574-20574/stimulus.openforbusiness D/AndroidRuntime: Shutting down VM
20574-20586/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] queueBuffer: BufferQueue has been abandoned
20574-23172/stimulus.openforbusiness I/Mint: NetSender: Sending data to url: https://3f83ef6b.api.splkmobile.com/1.0/3f83ef6b/ca5bde84a2e2c1d28119de1829bd0316/1/0
20574-20587/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] queueBuffer: BufferQueue has been abandoned
20574-20615/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] queueBuffer: BufferQueue has been abandoned
20574-20586/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] queueBuffer: BufferQueue has been abandoned
20574-20615/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] queueBuffer: BufferQueue has been abandoned
20574-20586/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] queueBuffer: BufferQueue has been abandoned
20574-20587/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] cancelBuffer: BufferQueue has been abandoned
20574-20615/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] cancelBuffer: BufferQueue has been abandoned
20574-20586/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] cancelBuffer: BufferQueue has been abandoned
20574-20587/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] cancelBuffer: BufferQueue has been abandoned
20574-20615/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] cancelBuffer: BufferQueue has been abandoned
20574-20586/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] cancelBuffer: BufferQueue has been abandoned
20574-20587/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] cancelBuffer: BufferQueue has been abandoned
20574-20615/stimulus.openforbusiness W/Camera-JNI: callback on dead camera object
20574-20574/stimulus.openforbusiness E/AndroidRuntime: FATAL EXCEPTION: main
                                                       Process: stimulus.openforbusiness, PID: 20574
                                                       java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 584064 bytes
                                                           at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3776)
                                                           at android.os.Handler.handleCallback(Handler.java:751)
                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                           at android.os.Looper.loop(Looper.java:154)
                                                           at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                                                        Caused by: android.os.TransactionTooLargeException: data parcel size 584064 bytes
                                                           at android.os.BinderProxy.transactNative(Native Method)
                                                           at android.os.BinderProxy.transact(Binder.java:615)
                                                           at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3700)
                                                           at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3768)
                                                           at android.os.Handler.handleCallback(Handler.java:751) 
                                                           at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                           at android.os.Looper.loop(Looper.java:154) 
                                                           at android.app.ActivityThread.main(ActivityThread.java:6123) 
                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 
20574-20586/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] queueBuffer: BufferQueue has been abandoned
20574-20574/stimulus.openforbusiness E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 584064)
20574-20574/stimulus.openforbusiness D/AndroidRuntime: Shutting down VM
20574-20586/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] queueBuffer: BufferQueue has been abandoned
20574-23172/stimulus.openforbusiness I/Mint: NetSender: Sending data to url: https://3f83ef6b.api.splkmobile.com/1.0/3f83ef6b/ca5bde84a2e2c1d28119de1829bd0316/1/0
20574-20587/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] queueBuffer: BufferQueue has been abandoned
20574-20615/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] queueBuffer: BufferQueue has been abandoned
20574-20586/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] queueBuffer: BufferQueue has been abandoned
20574-20615/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] queueBuffer: BufferQueue has been abandoned
20574-20586/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] queueBuffer: BufferQueue has been abandoned
20574-20587/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] cancelBuffer: BufferQueue has been abandoned
20574-20615/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] cancelBuffer: BufferQueue has been abandoned
20574-20586/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] cancelBuffer: BufferQueue has been abandoned
20574-20587/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] cancelBuffer: BufferQueue has been abandoned
20574-20615/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] cancelBuffer: BufferQueue has been abandoned
20574-20586/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] cancelBuffer: BufferQueue has been abandoned
20574-20587/stimulus.openforbusiness E/BufferQueueProducer: [SurfaceTexture-0-20574-0] cancelBuffer: BufferQueue has been abandoned
20574-20615/stimulus.openforbusiness W/Camera-JNI: callback on dead camera object
20574-20574/stimulus.openforbusiness E/AndroidRuntime: FATAL EXCEPTION: main
                                                       Process: stimulus.openforbusiness, PID: 20574
                                                       java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 584064 bytes
                                                           at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3776)
                                                           at android.os.Handler.handleCallback(Handler.java:751)
                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                           at android.os.Looper.loop(Looper.java:154)
                                                           at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                                                        Caused by: android.os.TransactionTooLargeException: data parcel size 584064 bytes
                                                           at android.os.BinderProxy.transactNative(Native Method)
                                                           at android.os.BinderProxy.transact(Binder.java:615)
                                                           at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3700)
                                                           at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3768)
                                                           at android.os.Handler.handleCallback(Handler.java:751) 
                                                           at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                           at android.os.Looper.loop(Looper.java:154) 
                                                           at android.app.ActivityThread.main(ActivityThread.java:6123) 
                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 

hope you find some clue from above log, reply soon !

**Comment by govindtank** [comment]
@guiguegon and issue #9 
i found some solution regarding this,
 refrences : http://stackoverflow.com/questions/11451393/what-to-do-on-transactiontoolargeexception 
http://stackoverflow.com/questions/39098590/android-os-transactiontoolargeexception-on-nougat


imported gallerymodule in my app, and edited the GalleryActivity.java
	
**Just Override this method on your gallery activity :**

```
@Override
protected void onSaveInstanceState(Bundle outState) {
    // below line to be commented to prevent crash on nougat.
    // http://blog.sqisland.com/2016/09/transactiontoolargeexception-crashes-nougat.html
    //
    //super.onSaveInstanceState(outState);
}
```

**Comment by guiguegon** [comment]
Thx @govindtank 

Currently I have no time to review all the issues, too much work at my job. Could you please make a PR with this change? Thx again

**Comment by govindtank** [comment]
Yesterday I found temporary solution, I tagged you in the comment, hope any
one who face the issue, will get some help from there.
